spring.application.name=QuickHost
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hiberate.format_sql=true
logging.file.name=application.log

server.servlet.context-path=/api/v1
